### ISSUE TITLE
False triggers caused by the wind charge

### ISSUE THREAD

**Issue by BAD7777** [Statuxia/LightAntiGrief#2]
If a beginner throws a wind charge into a shulker box or a chest, a message will appear stating that they have broken it. A wind charge cannot break a shulker box or a chest.

**Comment by BAD7777** [comment]
It seems the problem is due to CoreProtect. We'll figure it out for ourselves.

**Comment by Statuxia** [comment]
I add support only for 1.20.x, so I didn't check wind charge. I'll make support soon (in 1-3 days) for 1.21 and 1.19

**Comment by Statuxia** [comment]
https://github.com/PlayPro/CoreProtect/commit/3e8083becf119ff2b136e19cdb84bedc3a100075
CoreProtect issue
